# https://github.com/marketplace/actions/upload-a-release-asset
name: Release
on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:

    - name: Wait Apk build
      uses: fountainhead/action-wait-for-check@v1.0.0
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: "apk"

    - name: Download apk package
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        workflow: android.yml
        name: apk_package
        commit: ${{ github.sha }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Get apk name
      id: apk
      run: echo ::set-output name=apk::$(ls *.apk)

    - name: Upload Apk package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ steps.apk.outputs.apk }}
        asset_name: ${{ steps.apk.outputs.apk }}
        asset_content_type: application/vnd.android.package-archive
